---
- name: Step 00xxxxx software
  hosts: localhost
  gather_facts: False
  become: false
  tasks:
    - debug:
        msg: "Software tasks Started"

- hosts: all
  gather_facts: yes
  tasks:
    - name: Dump all variables
      local_action:
        module: template
        src: dumpall.j2
        dest: /tmp/ansible_dump.all
      run_once: true
      when: dump_vars|default(false)|bool

- name: Install Ansible automation controller
  hosts: bastions[0]
  gather_facts: false
  become: true

  tasks:

    - name: Install code-server
      include_role:
        name: vscode-server

    - name: create strong password for Tower and VScode
      set_fact:
        tower_admin_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"

    - name: New deploy_automationcontroller role needs password under different name
      set_fact:
        automationcontroller_admin_password: "{{ tower_admin_password }}"

    - name: Set vscode password to tower_admin_password
      set_fact:
        vscode_user_password: "{{ tower_admin_password }}"

    - name: Install Ansible automation controller
      include_role:
        name: deploy_automationcontroller

- name: Install license and LE certs on autoctl nodes
  hosts: automationcontroller
  gather_facts: false
  become: true

  tasks:

    - name: License autoctl nodes
      include_role:
        name: tower-license-injector
      run_once: true

    - name: Issue LE certs on autoctl nodes
      include_role:
        name: automation_controller_issue_cert

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Software checks completed successfully"
